# SPDX-License-Identifier: MIT OR Apache-2.0

monitor.alsa.rules = [
  {
    matches = [
      {
        device.bus = "pci"
        device.vendor.id = "0x1102"
        device.product.id = "0x0012"
      }
    ]
    actions = {
      update-props = {
        device.profile-set = "sound-blaster-ae5.conf"
      }
    }
  }
]
