#!/usr/bin/env bash
set -euo pipefail

# CXX-Qt's QML module is generated by the package build script. Building every
# feature for every binary makes that module leak into the unrelated GTK, CLI,
# and daemon link steps on linkers that enforce archive ordering strictly.
# Keep the two frontend feature sets in separate Cargo invocations instead.
cargo build "$@" \
	--release \
	--no-default-features \
	--features gui,daemon,outfx-lab \
	--bin ae5-control \
	--bin ae5ctl \
	--bin ae5d

cargo build "$@" \
	--release \
	--no-default-features \
	--features qml-gui,outfx-lab \
	--bin ae5-control-qml
