# SPDX-License-Identifier: MIT OR Apache-2.0

.include default.conf

[Mapping analog-stereo]
paths-output = analog-output analog-output-lineout analog-output-speaker sound-blaster-ae5-output-headphones analog-output-headphones-2
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping stereo-fallback]
paths-output = analog-output analog-output-lineout analog-output-speaker sound-blaster-ae5-output-headphones analog-output-headphones-2
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping mono-fallback]
paths-output = analog-output analog-output-lineout analog-output-speaker sound-blaster-ae5-output-headphones analog-output-headphones-2 analog-output-mono
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping analog-surround-21]
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping analog-surround-40]
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping analog-surround-41]
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping analog-surround-50]
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping analog-surround-51]
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in

[Mapping analog-surround-71]
paths-input = sound-blaster-ae5-input-microphone sound-blaster-ae5-input-front-microphone sound-blaster-ae5-input-line-in
