# SPDX-License-Identifier: MIT OR Apache-2.0

.include default.conf

[Mapping analog-stereo]
paths-output = analog-output analog-output-lineout analog-output-speaker sound-blaster-ae5-output-headphones analog-output-headphones-2

[Mapping stereo-fallback]
paths-output = analog-output analog-output-lineout analog-output-speaker sound-blaster-ae5-output-headphones analog-output-headphones-2

[Mapping mono-fallback]
paths-output = analog-output analog-output-lineout analog-output-speaker sound-blaster-ae5-output-headphones analog-output-headphones-2 analog-output-mono
